---
PRIMARY_DOMAIN: 'random-domain.com'
NGINX_SHARED_IPS: 
    - {'ip': '192.168.12.99', 'purpose': 'nginx default shared ip'}
    - {'ip': '192.168.12.19', 'purpose': 'ldaps shared ip'}
    - {'ip': '192.168.12.36', 'purpose': 'Proxmox shared ip'}
KEEPALIVED_SCRIPT_USER: 'deploy'

NGINX_HOSTS:
    - { 'HOSTNAME':'nginx-0', 'IP':'192.168.12.106', 'KEEPALIVED_PRIORITY': '102', 'STATE': 'MASTER' }
    - { 'HOSTNAME':'nginx-1', 'IP':'192.168.12.107', 'KEEPALIVED_PRIORITY': '101', 'STATE': 'BACKUP'  }
    - { 'HOSTNAME':'nginx-2', 'IP':'192.168.12.108', 'KEEPALIVED_PRIORITY': '100', 'STATE': 'BACKUP'  }

GENERATE_CERTS: no
VAULT_CERT_REQUEST_PATH: 'https://hc-vault.{{ PRIMARY_DOMAIN }}.com/v1/pki_int/'
CERT_PATH: '/etc/nginx/ssl'

OPEN_ADDITIONAL_UFW_PORTS: yes

IP_WHITELIST_LOCKED_DOWN:
    - '192.168.12.0/24'
    - '10.101.21.0/24'

IP_WHITELIST_ALLOW_HOMEWOMEY:
    - '192.168.12.0/24'
    - '10.101.21.0/24'
    - '10.101.31.0/24'

NGINX_SITES:
    - DOMAIN: '{{ PRIMARY_DOMAIN }}'
      SUBDOMAINS: [
        { 'name': 'portainer', mode: 'http', 'ip_addresses': {'192.168.12.70'}, 'port': '9000', whitelist_ips: "{{ IP_WHITELIST_LOCKED_DOWN }}", additional_parameters: {}},
        { 'name': 'jellyfin', mode: 'http', 'ip_addresses': {'192.168.12.44'}, 'port': '8096', whitelist_ips: "{{ IP_WHITELIST_ALLOW_HOMEWOMEY }}", additional_parameters: {} },
        { 'name': 'ubooquity', mode: 'http', 'ip_addresses': {'192.168.12.70'}, 'port': '2202', whitelist_ips: "{{ IP_WHITELIST_LOCKED_DOWN }}", additional_parameters: {} },
        { 'name': 'ubooquity-admin', mode: 'http', 'ip_addresses': {'192.168.12.70'}, 'port': '2203', whitelist_ips: "{{ IP_WHITELIST_LOCKED_DOWN }}", additional_parameters: {} },
        { 'name': 'guacamole', mode: 'http', 'ip_addresses': {'192.168.12.49'}, 'port': '8080', whitelist_ips: "{{ IP_WHITELIST_LOCKED_DOWN }}", additional_parameters: {} },
        { 'name': 'yt-dl', mode: 'http', 'ip_addresses': {'192.168.12.70'}, 'port': '8686', whitelist_ips: "{{ IP_WHITELIST_LOCKED_DOWN }}", additional_parameters: {} },
        { 'name': 'pyload', mode: 'http', 'ip_addresses': {'192.168.12.65'}, 'port': '8000', whitelist_ips: "{{ IP_WHITELIST_LOCKED_DOWN }}", additional_parameters: {} },
        { 'name': 'nextcloud', mode: 'http', 'ip_addresses': {'192.168.12.45'}, 'port': '80', whitelist_ips: "{{ IP_WHITELIST_ALLOW_HOMEWOMEY }}", additional_parameters: {'proxy_set_header Host $host', 'proxy_set_header X-Real-IP $remote_addr', 'proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for', 'proxy_set_header X-Forwarded-Proto $scheme', 'client_max_body_size 0', 'add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"' } },
        { 'name': 'radarr', mode: 'http', 'ip_addresses': {'192.168.12.65'}, 'port': '7878', whitelist_ips: "{{ IP_WHITELIST_LOCKED_DOWN }}", additional_parameters: {} },
        { 'name': 'sonarr', mode: 'http', 'ip_addresses': {'192.168.12.65'}, 'port': '8989', whitelist_ips: "{{ IP_WHITELIST_LOCKED_DOWN }}", additional_parameters: {} },
        { 'name': 'lidarr', mode: 'http', 'ip_addresses': {'192.168.12.65'}, 'port': '8686', whitelist_ips: "{{ IP_WHITELIST_LOCKED_DOWN }}", additional_parameters: {} },
        { 'name': 'jackett', mode: 'http', 'ip_addresses': {'192.168.12.65'}, 'port': '9117', whitelist_ips: "{{ IP_WHITELIST_LOCKED_DOWN }}", additional_parameters: {} },
        { 'name': 'pirate-trans', mode: 'http', 'ip_addresses': {'192.168.12.65'}, 'port': '9091', whitelist_ips: "{{ IP_WHITELIST_LOCKED_DOWN }}", additional_parameters: {} },
        { 'name': 'focalboard', mode: 'http', 'ip_addresses': {'192.168.12.70'}, 'port': '8745', whitelist_ips: "{{ IP_WHITELIST_LOCKED_DOWN }}", additional_parameters: {} },
        { 'name': 'netbox', mode: 'http', 'ip_addresses': {'192.168.12.72'}, 'port': '80', whitelist_ips: "{{ IP_WHITELIST_LOCKED_DOWN }}", additional_parameters: {} },
        { 'name': 'uptime-kuma', mode: 'http', 'ip_addresses': {'192.168.12.70'}, 'port': '3001', whitelist_ips: "{{ IP_WHITELIST_LOCKED_DOWN }}", additional_parameters: {'proxy_set_header   X-Real-IP $remote_addr', 'proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for', 'proxy_http_version 1.1', 'proxy_set_header   Upgrade $http_upgrade', 'proxy_set_header   Connection "upgrade"'} },
        { 'name': 'gotify', mode: 'http', 'ip_addresses': {'192.168.12.70'}, 'port': '3281', whitelist_ips: "{{ IP_WHITELIST_LOCKED_DOWN }}", additional_parameters: {} },
        { 'name': 'bazarr', mode: 'http', 'ip_addresses': {'192.168.12.65'}, 'port': '6767', whitelist_ips: "{{ IP_WHITELIST_LOCKED_DOWN }}", additional_parameters: {} },
        { 'name': 'home', mode: 'http', 'ip_addresses': {'192.168.12.81'}, 'port': '4212', whitelist_ips: "{{ IP_WHITELIST_LOCKED_DOWN }}", additional_parameters: {} },
        { 'name': 'docs', mode: 'http', 'ip_addresses': {'192.168.12.48'}, 'port': '80', whitelist_ips: "{{ IP_WHITELIST_LOCKED_DOWN }}", additional_parameters: {} },
        { 'name': 'pve', mode: 'https', 'ip_addresses': {'192.168.12.32','192.168.12.33','192.168.12.34'}, 'port': '8006', 'prioritise_first': 'yes', whitelist_ips: "{{ IP_WHITELIST_LOCKED_DOWN }}", additional_parameters: {'proxy_http_version 1.1','proxy_set_header Upgrade $http_upgrade','proxy_set_header Connection "upgrade"'} },
        { 'name': 'consul', mode: 'https', 'ip_addresses': {'192.168.12.110','192.168.12.111','192.168.12.112'}, 'port': '8501', 'prioritise_first': 'no', whitelist_ips: "{{ IP_WHITELIST_LOCKED_DOWN }}", additional_parameters: {} }
      ]
      LOAD_BALANCER:  [
        {'name': 'ldaps', ips: {'192.168.12.10','192.168.12.11'}, port: '636', balance_algorithm: 'least_conn'},
        # {'name': 'consul', ips: {'192.168.12.110','192.168.12.111','192.168.12.112'}, port: '8501', balance_algorithm: 'least_conn'}
      ]
    # - DOMAIN: whyitno.work
    #   SUBDOMAINS: [
    #     { 'name': 'bleh', mode: 'http', 'ip': '192.168.12.70', 'port': '9000', whitelist_ips: {} },
    #     { 'name': 'blue', mode: 'http', 'ip': '192.168.12.44', 'port': '8096', whitelist_ips: "{{ IP_WHITELIST_LOCKED_DOWN }}", additional_parameters: {} },
    #     { 'name': 'meh', mode: 'http', 'ip': '192.168.12.70', 'port': '2202', whitelist_ips: "{{ IP_WHITELIST_LOCKED_DOWN }}", additional_parameters: {} }
    #   ]
      #   LOAD_BALANCER:  [
      #   {'name': 'ldaps', ips: {'192.168.12.10','192.168.12.11'}, port: '636', balance_algorithm: 'least_conn'}
      # ]
