---
PRIMARY_DOMAIN: 'domain.com'
NGINX_SHARED_IPS: 
    - {'ip': '10.10.11.xx', 'purpose': 'nginx default shared ip'}
    - {'ip': '10.10.11.x', 'purpose': 'ldaps shared ip'}
    - {'ip': '10.10.11.xx', 'purpose': 'Proxmox shared ip'}
KEEPALIVED_SCRIPT_USER: 'deploy'

NGINX_HOSTS:
    - { 'HOSTNAME':'nginx-0', 'IP':'10.10.11.xx', 'KEEPALIVED_PRIORITY': '102', 'STATE': 'MASTER' }
    - { 'HOSTNAME':'nginx-1', 'IP':'10.10.11.xx', 'KEEPALIVED_PRIORITY': '101', 'STATE': 'BACKUP'  }
    - { 'HOSTNAME':'nginx-2', 'IP':'10.10.11.xx', 'KEEPALIVED_PRIORITY': '100', 'STATE': 'BACKUP'  }

GENERATE_CERTS: no
VAULT_CERT_REQUEST_PATH: 'https://hc-vault.{{ PRIMARY_DOMAIN }}.com/v1/pki_int/'
CERT_PATH: '/etc/nginx/ssl'

OPEN_ADDITIONAL_UFW_PORTS: yes

NGINX_SITES:
    - DOMAIN: '{{ PRIMARY_DOMAIN }}'
      SUBDOMAINS: [
        { 'name': 'portainer', mode: 'http', 'ip_addresses': {'10.10.11.70'}, 'port': '9000', whitelist_ips: {'10.109.11.0/24', '10.108.20.0/24'}, additional_parameters: {}},
        { 'name': 'jellyfin', mode: 'http', 'ip_addresses': {'10.10.11.44'}, 'port': '8096', whitelist_ips: {}, additional_parameters: {} },
        { 'name': 'guacamole', mode: 'http', 'ip_addresses': {'10.10.11.49'}, 'port': '8080', whitelist_ips: {}, additional_parameters: {} },
        { 'name': 'yt-dl', mode: 'http', 'ip_addresses': {'10.10.11.70'}, 'port': '8686', whitelist_ips: {}, additional_parameters: {} },
        { 'name': 'pyload', mode: 'http', 'ip_addresses': {'10.10.11.65'}, 'port': '8000', whitelist_ips: {}, additional_parameters: {} },
        { 'name': 'nextcloud', mode: 'http', 'ip_addresses': {'10.10.11.45'}, 'port': '80', whitelist_ips: {}, additional_parameters: {'proxy_set_header Host $host', 'proxy_set_header X-Real-IP $remote_addr', 'proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for', 'proxy_set_header X-Forwarded-Proto $scheme', 'client_max_body_size 0', 'add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"' } },
        { 'name': 'focalboard', mode: 'http', 'ip_addresses': {'10.10.11.70'}, 'port': '8745', whitelist_ips: {}, additional_parameters: {} },
        { 'name': 'netbox', mode: 'http', 'ip_addresses': {'10.10.11.72'}, 'port': '80', whitelist_ips: {}, additional_parameters: {} },
        { 'name': 'uptime-kuma', mode: 'http', 'ip_addresses': {'10.10.11.70'}, 'port': '3001', whitelist_ips: {}, additional_parameters: {'proxy_set_header   X-Real-IP $remote_addr', 'proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for', 'proxy_http_version 1.1', 'proxy_set_header   Upgrade $http_upgrade', 'proxy_set_header   Connection "upgrade"'} },
        { 'name': 'pve', mode: 'https', 'ip_addresses': {'10.10.11.32','10.10.11.33','10.10.11.34'}, 'port': '8006', 'prioritise_first': 'yes', whitelist_ips: {}, additional_parameters: {'proxy_http_version 1.1','proxy_set_header Upgrade $http_upgrade','proxy_set_header Connection "upgrade"'} }
      ]
      LOAD_BALANCER:  [
        {'name': 'ldaps', ips: {'10.10.11.10','10.10.11.11'}, port: '636', balance_algorithm: 'least_conn'}
      ]
    # - DOMAIN: whyitno.work
    #   SUBDOMAINS: [
    #     { 'name': 'bleh', mode: 'http', 'ip': '10.10.11.70', 'port': '9000', whitelist_ips: {} },
    #     { 'name': 'blue', mode: 'http', 'ip': '10.10.11.44', 'port': '8096', whitelist_ips: {}, additional_parameters: {} },
    #     { 'name': 'meh', mode: 'http', 'ip': '10.10.11.70', 'port': '2202', whitelist_ips: {}, additional_parameters: {} }
    #   ]
      #   LOAD_BALANCER:  [
      #   {'name': 'ldaps', ips: {'10.10.11.10','10.10.11.11'}, port: '636', balance_algorithm: 'least_conn'}
      # ]
