---
- name: Include prep.yml
  include_tasks: prep.yml

- name: Include nginx.yml
  include_tasks: nginx.yml

- name: Include ssl-wildcard.yml
  include_tasks: ssl-wildcard.yml
  when: not GENERATE_CERTS

- name: Include ssl-root-cert.yml
  include_tasks: ssl-root-cert.yml
  when: GENERATE_CERTS
  no_log: yes

- name: Generate ssl certs
  block:
    - name: Include task
      include_tasks: ssl-cert-request.yml
      with_items: "{{ NGINX_SITES }}"
  when: GENERATE_CERTS
  no_log: yes

- name: Include keepalived.yml
  include_tasks: keepalived.yml

- name: Reboot
  reboot: